"""Add plaintext_password fields

Revision ID: dfd4d6286793
Revises: 
Create Date: 2026-04-16 14:06:22.039812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd4d6286793'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index('idx_asset_room_status', ['room_id', 'status'], unique=False)

    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plaintext_password', sa.String(length=255), nullable=True))

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index('idx_ticket_professional_status', ['assigned_professional_id', 'status'], unique=False)
        batch_op.create_index('idx_ticket_reporter_created', ['reporter_id', 'created_at'], unique=False)
        batch_op.create_index('idx_ticket_status_created', ['status', 'created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plaintext_password', sa.String(length=255), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'student'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'student'::character varying"))
        batch_op.drop_column('plaintext_password')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index('idx_ticket_status_created')
        batch_op.drop_index('idx_ticket_reporter_created')
        batch_op.drop_index('idx_ticket_professional_status')

    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.drop_column('plaintext_password')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index('idx_asset_room_status')

    # ### end Alembic commands ###
